import { createHash } from 'node:crypto';
import { canonicalSet, jcsBytes } from './canonical.mjs';
import { assessClaim, assessRisk, assessRecommendation, reduceRelease } from './claims.mjs';

const fail=()=>{throw new TypeError('INVALID_SOURCE_MATERIAL');};
const exact=(value,keys)=>value!==null&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).length===keys.length&&keys.every((key)=>Object.hasOwn(value,key));
const text=(value)=>typeof value==='string'&&value.length>0&&value.normalize('NFC')===value;
const copy=(value)=>JSON.parse(jcsBytes(value).toString('utf8'));
const hash=(domain,value)=>createHash('sha256').update(domain).update(jcsBytes(value)).digest('hex');
const sourceDigest=(value)=>createHash('sha256').update(jcsBytes(value)).digest('hex');
const publicId=(prefix,domain,body)=>prefix+'_'+hash(domain,body).slice(0,32);
const strings=(items)=>{if(!Array.isArray(items)||!items.every(text))fail();return canonicalSet(items,(item)=>item);};
const invalidCore=(core)=>Array.isArray(core?.reason_codes)&&core.reason_codes.includes('INVALID_INPUT');
const lowerHex64=(value)=>typeof value==='string'&&/^[0-9a-f]{64}$/.test(value);
const FINDING_KEYS=['emission_reason_code','finding_id','finding_type','fingerprint','fingerprint_full_digest','rule_id','rule_version'];
const FINGERPRINT_KEYS=['behavior_version','canonical_target_locator','claim_key','emission_reason_code','finding_type','rule_id','rule_version','scenario_binding_ids','schema_version','target_snapshot_digest'];
const CLAIM_KEY_KEYS=['context_id','population_id','predicate_id','time_scope_id'];
const FINDING_TYPES=Object.freeze({RULE_CHECK_FAILED:null,RULE_PARTIAL:'unknown',RELEASE_CRITICAL_PARTIAL:'escalation',RULE_NOT_RUN:'unknown',RELEASE_CRITICAL_NOT_RUN:'escalation',RULE_UNKNOWN:'unknown',RELEASE_CRITICAL_UNKNOWN:'escalation',RELEASE_CRITICAL_EVALUATION_ERROR:'escalation'});
const FINDING_OUTCOMES=Object.freeze({RULE_CHECK_FAILED:'fail',RULE_PARTIAL:'partial',RELEASE_CRITICAL_PARTIAL:'partial',RULE_NOT_RUN:'not_run',RELEASE_CRITICAL_NOT_RUN:'not_run',RULE_UNKNOWN:'unknown',RELEASE_CRITICAL_UNKNOWN:'unknown',RELEASE_CRITICAL_EVALUATION_ERROR:'evaluation_error'});
const validClaimKey=(value)=>value===null||(exact(value,CLAIM_KEY_KEYS)&&CLAIM_KEY_KEYS.every((key)=>text(value[key])));
const normalizeTask5Finding=(finding)=>{const value=copy(finding);if(!exact(value,FINDING_KEYS)||!text(value.rule_id)||!text(value.rule_version)||!text(value.finding_type)||!Object.hasOwn(FINDING_TYPES,value.emission_reason_code))fail();const requiredType=FINDING_TYPES[value.emission_reason_code];if(requiredType!==null&&value.finding_type!==requiredType)fail();const fp=value.fingerprint;if(!exact(fp,FINGERPRINT_KEYS)||fp.schema_version!=='finding-v1'||!text(fp.behavior_version)||!text(fp.rule_id)||!text(fp.rule_version)||!text(fp.finding_type)||!text(fp.canonical_target_locator)||!lowerHex64(fp.target_snapshot_digest)||!Array.isArray(fp.scenario_binding_ids)||fp.scenario_binding_ids.length===0||!validClaimKey(fp.claim_key))fail();const scenarios=strings(fp.scenario_binding_ids);if(!jcsBytes(scenarios).equals(jcsBytes(fp.scenario_binding_ids)))fail();if(fp.rule_id!==value.rule_id||fp.rule_version!==value.rule_version||fp.finding_type!==value.finding_type||fp.emission_reason_code!==value.emission_reason_code)fail();const full=hash('ux-skill:finding:v1',fp);if(value.fingerprint_full_digest!==full||value.finding_id!=='f_'+full.slice(0,32))fail();return value;};
const riskSummaryFromFinding=(finding)=>({mandatory_fail:false,hard_unsat:false,hard_decision:finding.finding_type==='block'?'block':finding.finding_type==='escalation'?'escalation':'none',release_critical:finding.emission_reason_code.startsWith('RELEASE_CRITICAL_'),outcome:FINDING_OUTCOMES[finding.emission_reason_code]});
const normalizeClaimSource=(source)=>{const value=copy(source);if(!exact(value,['claim','evidence','policy']))fail();if(!exact(value.claim,['claim_id','claim_kind','relation_kind','predicate_id','population_id','context_id','time_scope_id','subject_id','value','evidence_refs']))fail();value.claim.evidence_refs=strings(value.claim.evidence_refs);if(!exact(value.evidence,['checks','selection_status','contradiction_status','measured_covariation','verifiable_observation','prediction_observed_outcome_pair','intervention_id','counterfactual_id','effect_estimand_id','future_target_id'])||!Array.isArray(value.evidence.checks))fail();value.evidence.checks=value.evidence.checks.map((row)=>{if(!exact(row,['required_check_id','status','dependency_cluster_id','evidence_refs']))fail();return{...row,evidence_refs:strings(row.evidence_refs)};});value.evidence.checks=canonicalSet(value.evidence.checks,(row)=>[row.required_check_id,row.dependency_cluster_id]);if(!exact(value.policy,['policy_id','claim_kind','required_checks'])||!Array.isArray(value.policy.required_checks))fail();value.policy.required_checks=canonicalSet(value.policy.required_checks,(row)=>row.required_check_id);const core=assessClaim(value.claim,value.evidence,value.policy);if(invalidCore(core)||core.reason_codes.includes('POLICY_ROW_MISSING'))fail();return{value,core};};
const normalizeRiskSource=(source,evaluationOutput)=>{const value=copy(source);if(!exact(value,['finding_id','finding','context'])||!/^f_[0-9a-f]{32}$/.test(value.finding_id))fail();const embedded=normalizeTask5Finding(value.finding);if(value.finding_id!==embedded.finding_id)fail();const output=copy(evaluationOutput);if(output===null||typeof output!=='object'||Array.isArray(output)||!Array.isArray(output.findings))fail();const owners=output.findings.filter((finding)=>finding!==null&&typeof finding==='object'&&finding.finding_id===value.finding_id);if(owners.length!==1)fail();const owner=normalizeTask5Finding(owners[0]);if(!jcsBytes(owner).equals(jcsBytes(embedded)))fail();const core=assessRisk(riskSummaryFromFinding(owner),value.context);if(core.reason_code==='INVALID_INPUT')fail();return{value:{finding_id:value.finding_id,finding:owner,context:value.context},core};};
const normalizeRecommendationSource=(source)=>{const value=copy(source);if(!exact(value,['parts','selected_policy_registry_row'])||!exact(value.selected_policy_registry_row,['policy_id','version','status'])||!text(value.selected_policy_registry_row.policy_id)||!text(value.selected_policy_registry_row.version)||value.selected_policy_registry_row.status!=='effective')fail();const core=assessRecommendation(value.parts);if(invalidCore(core))fail();return{value,core};};
const normalizeReleaseSource=(source)=>{const value=copy(source);if(!exact(value,['derived_gates','selection','authority','critical_tail_evidence','conditions'])||!Array.isArray(value.derived_gates)||!Array.isArray(value.conditions)||!exact(value.selection,['status'])||!exact(value.authority,['complete'])||!exact(value.critical_tail_evidence,['critical_status','tail_unknown']))fail();value.derived_gates=strings(value.derived_gates);value.conditions=canonicalSet(value.conditions,(row)=>[row.predicate,row.owner,row.deadline,row.verification_method]);const parts={gates:value.derived_gates,selection:value.selection.status,authority_complete:value.authority.complete,critical_status:value.critical_tail_evidence.critical_status,tail_unknown:value.critical_tail_evidence.tail_unknown,conditions:value.conditions};const core=value.derived_gates.length===1&&value.derived_gates[0]==='no_release'?{status:'no_release',next_action:'complete_snapshot_closure',conditions:value.conditions,reason_code:'SNAPSHOT_CLOSURE_UNAVAILABLE'}:reduceRelease(parts);if(core.reason_code==='INVALID_INPUT')fail();return{value,core};};
export const materializeClaimAssessment=(source)=>{const {value,core}=normalizeClaimSource(source);const body={source_material_digest:sourceDigest(value),claim_id:core.claim_id,policy_id:core.policy_id,admissible_conclusion:core.status,assessed_predicate:core.assessed_predicate,checks:core.checks,dimension_scores:core.dimension_scores,evidence_grade:core.evidence_grade,reason_codes:strings(core.reason_codes)};return{claim_assessment_id:publicId('ca','ux-skill:claim-assessment-public:v1',body),...body};};
export const materializeRiskAssessment=(source,evaluationOutput)=>{const {value,core}=normalizeRiskSource(source,evaluationOutput);const body={source_material_digest:sourceDigest(value),finding_id:value.finding_id,status:'complete',decision:core.decision,severity:value.context.severity,likelihood:value.context.likelihood,exposure:value.context.exposure,reversibility:value.context.reversibility,reason_codes:[core.reason_code]};return{risk_assessment_id:publicId('ra','ux-skill:risk-assessment:v1',body),...body};};
export const materializeRecommendationAssessment=(source)=>{const {value,core}=normalizeRecommendationSource(source);let recommendation=null;if(core.recommendation){const recBody={action:core.recommendation.action,strength:core.recommendation.strength};recommendation={recommendation_id:publicId('rec','ux-skill:recommendation:v1',recBody),...recBody};}const body={source_material_digest:sourceDigest(value),status:'complete',action_id:value.parts.action.action_id,authority_ceiling:core.ceilings.authority,evidence_ceiling:core.ceilings.evidence,risk_ceiling:core.ceilings.risk,reversibility_ceiling:core.ceilings.reversibility,minimum_ceiling:core.minimum_ceiling,strength:core.strength,output_kind:core.output_kind,recommendation,research_question:core.research_question,policy_version:value.selected_policy_registry_row.version,reason_codes:strings(core.reason_codes)};return{recommendation_assessment_id:publicId('rma','ux-skill:recommendation-assessment:v1',body),...body};};
export const materializeReleaseRecommendation=(source)=>{const {value,core}=normalizeReleaseSource(source);const conditions=core.conditions.map((row)=>({condition_id:publicId('rc','ux-skill:release-condition:v1',row),...row})).sort((a,b)=>Buffer.compare(Buffer.from(a.condition_id),Buffer.from(b.condition_id)));const body={source_material_digest:sourceDigest(value),status:core.status,next_action:core.next_action,condition_ids:conditions.map((row)=>row.condition_id),conditions,reason_code:core.reason_code};return{release_recommendation_id:publicId('rr','ux-skill:release-recommendation:v1',body),...body};};
const materializers={claim:materializeClaimAssessment,risk:materializeRiskAssessment,recommendation:materializeRecommendationAssessment,release:materializeReleaseRecommendation};
export const verifyPublicMaterialization=(kind,source,publicValue,evaluationOutput)=>{try{const materialize=materializers[kind];if(!materialize)return false;return jcsBytes(materialize(source,evaluationOutput)).equals(jcsBytes(publicValue));}catch{return false;}};

export const createSemanticProjection=(evaluationOutput)=>{
 const value=copy(evaluationOutput);
 if(!exact(value,['schema_version','behavior_version','input_digest','evaluator_digest','run_status','validation_errors','rule_evaluations','findings','run_issues','claim_assessments','risk_assessments','recommendation_assessments','release_recommendation','resolution_traces','inquiry_validation','coverage_gaps'])||value.validation_errors.length!==0)fail();
 const projection={schema_version:value.schema_version,behavior_version:value.behavior_version,input_digest:value.input_digest,evaluator_digest:value.evaluator_digest,run_status:value.run_status,rule_evaluations:value.rule_evaluations,findings:value.findings,run_issues:value.run_issues,claim_assessments:value.claim_assessments,risk_assessments:value.risk_assessments,recommendation_assessments:value.recommendation_assessments,release_recommendation:value.release_recommendation,resolution_traces:value.resolution_traces,inquiry_validation:value.inquiry_validation,coverage_gaps:value.coverage_gaps};
 return{...projection,semantic_digest:hash('ux-skill:semantic:v1',projection)};
};
